# Generated by Django 6.0.4 on 2026-06-12 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_tag_task_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["owner", "completed"], name="task_owner_completed_idx"
            ),
        ),
    ]
